import Head from "next/head"
import { useEffect, useMemo, useState } from "react"

export default function Home() {
  const stacks = useMemo(() => ["web", "game", "Front-end"], [])
  const [selectedStack, setSelectedStack] = useState(stacks[0])
  const [typing, setTyping] = useState("isTyping")

  const [displayedStack, setDisplayedStack] = useState("")

  const sleep = (ms: number) =>
    new Promise((resolve) => {
      setTimeout(resolve, ms)
    })

  useEffect(() => {
    const timeout = setTimeout(() => {
      if (typing === "isTyping" && displayedStack !== selectedStack) {
        setDisplayedStack(selectedStack.slice(0, displayedStack.length + 1))
      } else if (displayedStack === selectedStack && typing === "isTyping") {
        sleep(2000).then(() => {
          setTyping("isDeleting")
        })
      } else if (
        (displayedStack === selectedStack && typing === "isDeleting") ||
        typing === "isDeleting"
      ) {
        setDisplayedStack(selectedStack.slice(0, displayedStack.length - 1))

        if (displayedStack.length <= 1) {
          setTyping("isTyping")
          setSelectedStack(
            selectedStack === stacks[stacks.length - 1]
              ? stacks[0]
              : stacks[stacks.indexOf(selectedStack) + 1]
          )
        }
      }
    }, 150)
    return () => clearTimeout(timeout)
  }, [displayedStack, selectedStack, stacks, typing])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen flex-col items-center justify-center">
        <div className="text-5xl text-center lg:w-[22rem]">
          Hello, I am
          <h2 className="flex text-center justify-between px-6 lg:px-0 mt-5 font-medium">
            <span className="text-[#481380]">Mateus</span> Galdino
          </h2>
        </div>
        <div className="text-center">
          <p className="text-3xl font-medium">
            A{" "}
            <span className="text-[#481380] after:content-['|'] after:animate-blinking">
              {displayedStack}
            </span>{" "}
            developer
          </p>
        </div>
      </div>
    </>
  )
}
